spring:
  datasource:
    url: jdbc:mysql://mysql-37152553-khoihuynh8686-0fc0.aivencloud.com:14223/social_media?createDatabaseIfNotExist=true
    username: avnadmin
    password: AVNS_I3wM0Zygn0j41RQhF8j
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
server:
  port: 8081